# 应用名称
spring:
  application:
    name: doris_postpay
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2b8&characterEncoding=utf-8
    username: root
    password: 111111




#端口路径配置
server:
  port: 8081
  context-path: /api


# mybatis 配置
# mappers.xml文件配置
mybatis:
  mapper-locations: classpath*:mybatis/mappers/*.xml
  # PO包路径配置
  type-aliases-package: com.gtxy.yyf.doris_postpay
  # 驼峰命名转换xx_xx xxXx
  configuration:
    map-underscore-to-camel-case: true
